Repository corca-ai/cds, pull requests merged in 2024-06, with the labels that each got.

#76 NONE) docs: add readme
  README.md
Labels: documentation

#77 NONE) fix: fix component export issue
  package.json
  src/components/index.ts
  src/index.ts
Labels: bug

#78 NONE) chore: modify the global.css file to include it in the build output
  .storybook/preview.js
  README.md
  package.json
  pnpm-lock.yaml
  src/index.ts
  vite.config.ts
Labels: operations

#79 ADCIO-3707) fix: fix prettier version and type in topbar
  package.json
  pnpm-lock.yaml
  src/components/Topbar/ProfileMenu.tsx
  src/stories/Topbar.stories.tsx
Labels: fix

#80 NONE) fix: fix typing
  package.json
  src/components/Topbar/ProfileMenu.tsx
  src/components/Topbar/index.tsx
Labels: fix

#81 NONE) chore: fix emotion error
  package.json
  pnpm-lock.yaml
  vite.config.ts
Labels: operations

#84 ADCIO-4010) feat: add select with icon and story
  package.json
  src/components/Select/SelectInput.tsx
  src/stories/Select.stories.tsx
Labels: feature request

#83 ADCIO-3917) fix: fix table tr state style issue
  src/components/Table/Tr.tsx
  src/stories/Table.stories.tsx
Labels: fix

#82 ADCIO-4008) feat: add multi select
  package.json
  src/components/Select/MultiSelect.tsx
  src/components/Select/MultiSelectInput.tsx
  src/components/Select/OptionList.tsx
  src/components/Select/Select.tsx
  src/components/Select/SelectInput.tsx
  src/components/Select/index.ts
  src/stories/Select.stories.tsx
Labels: feature request

#86 Fix) fix: fix select default type to use number and string
  package.json
  src/components/Select/MultiSelect.tsx
  src/components/Select/MultiSelectInput.tsx
  src/components/Select/OptionList.tsx
  src/components/Select/Select.tsx
Labels: fix

#87 NONE) fix: fix type err in storybook select
  package.json
  src/stories/Select.stories.tsx
Labels: fix

#88 NONE) feat: add multi select init value available
  package.json
  src/components/Select/MultiSelect.tsx
Labels: fix

#89 ADCIO-3975) feat: fix element tag
  package.json
  src/components/Select/MultiSelectInput.tsx
  src/components/Select/OptionList.tsx
  src/components/Select/SelectInput.tsx
Labels: bug

#90 NONE) fix: fix button to element
  package.json
  src/components/Select/MultiSelectInput.tsx
Labels: fix

#91 NONE) fix: fix multiselect onselect
  package.json
  src/components/Select/MultiSelect.tsx
Labels: fix

#92 NONE) fix: fix multi select single pick
  package.json
  src/components/Select/MultiSelect.tsx
  src/components/Select/MultiSelectInput.tsx
Labels: fix

#94 NONE) fix: fix badge style
  package.json
  src/components/Badge/index.tsx
  src/stories/Badge.stories.tsx
Labels: fix
